### ISSUE TITLE
Is the firebase dynamic link really correct?

### ISSUE THREAD

**Issue by andidev** [invertase/react-native-firebase-docs#192]
According to the dynamics link docs [here](https://github.com/invertase/react-native-firebase-docs/blob/v5.x.x/docs/links/android.md#add-the-dependency) one should add the firebase-invites gradle dependency
```
implementation "com.google.firebase:firebase-invites:17.0.0"
```

but according to the google firebase docs [here](https://firebase.google.com/docs/dynamic-links/android/create#set-up-firebase-and-the-dynamic-links-sdk) one should add the new firebase-dynamic-links gradle dependency
```
implementation 'com.google.firebase:firebase-dynamic-links:17.0.0'
```

which one is it or does both work?

**Comment by mikehardy** [comment]
Both. Why? Because invites is going away as a service, but there is still an internal (but public) API that react-native-firebase uses in order to determine if an inbound dynamic link was an invite or not
