### ISSUE TITLE
I can't login with phone number using this code.

### ISSUE THREAD

**Issue by fullstact69** [invertase/react-native-firebase-docs#228]
I have tried to login with phone number to firebase using the same codes.
But I can't login with phone number.
How can I resolve this issue?

**Comment by guojutaoo** [comment]
Same issue here, the signinwithphonenumber now requires a appverifier which can only get from web...

**Comment by fullstact69** [comment]
Firebase sent sms almost 6 times. After that, Firebase didn't send sms and I get the error such as "limited request can't be accepted".  Let me know this limitation.

**Comment by guojutaoo** [comment]
Oh I haven't get the sms yet, I got stuck for a few days by the appveirifier, one of the parameter of firebase.auth.signinwithphonenumber function, can you tell me how to you manage to do that? Thanks a lot!

**Comment by mikehardy** [comment]
They're just throttling you if you got the SMS first and are now getting an error. They've very quick to throttle SMS since it can be used so easily to harrass people

**Comment by fullstact69** [comment]
How to update phone number? I have tried to use updatePhoneNumber API.
But I am not clear yet for this API.

**Comment by guojutaoo** [comment]
I figured it out, just the API for signing in with your phone number, thanks though:)

**Comment by mikehardy** [comment]
@guojutaoo this was someone else's issue that you sort of hijacked ;-), I'm not sure what the status is. @fullstact69 I'm going to close this but if you have an issue still please open a new one **following the template** so we can help
