### ISSUE TITLE
Can not setBadge when app is in background

### ISSUE THREAD

**Issue by duyenhang2019** [invertase/react-native-firebase-docs#236]
When App is in foreground, it's work.
But when app is in background, I can not set badge number for app icon.
firebase.messaging().onMessage(async (message) => {
    firebase.notifications().setBadge(1)
}

**Comment by mikehardy** [comment]
Hi there! Wrong repo -> this is the docs repo, you want the main react-native-firebase repo. Follow the template carefully.

That said, badging works on ios but on android it is a terrible hack supported as possible by a 3rd party library (ShortcutBadger) and dependent on vendor APIs that may or may not exist - which is to say, I would not make it a hard requirement of any app, thus it's success or failure really shouldn't be considered a bug anywhere. Badging just isn't an android thing.

**Comment by duyenhang2019** [comment]
It's not work when on ios app at background. I push a silent message and set badge number when the app got silent push notification. But when app on background, it's not set badge. (It's work well when app on foreground)
