### ISSUE TITLE
Unable to load ads using this

### ISSUE THREAD

**Issue by priyankagupta23pg** [invertase/react-native-firebase-docs#253]
Unable to load ads 3 error 
    "react-native-firebase": "^5.6.0",

I am using this code
const Banner = firebase.admob.Banner;
    const AdRequest = firebase.admob.AdRequest;
    const request = new AdRequest();
I am using live bannerID
<Banner
          unitId='bannerID'
          size={'SMART_BANNER'}
          request={request.build()}
          onAdLoaded={() => {
            console.log('Advert loaded');
          }}
        />

**Comment by mikehardy** [comment]
No template / wrong repo, please open an issue in main react-native-firebase repo, following the template
