### ISSUE TITLE
An error in the website on rnfirebase.io website cloud messaging monitor token generation code

### ISSUE THREAD

**Issue by richieteh94** [invertase/react-native-firebase-docs#75]
Hi, on this rnfirebase.io doc website https://rnfirebase.io/docs/v4.2.x/messaging/device-token monitor token code as below is wrong.
```
componentDidMount() {
    this.onTokenRefreshListener = firebase.messaging().onTokenRefresh(fcmToken: string => {
        // Process your token as required
    });
}
```

where the I think it should be something like this

```
componentDidMount() {
    this.onTokenRefreshListener = firebase.messaging().onTokenRefresh((fcmToken: string) => {
        // Process your token as required
    });
}
```

or this

```
componentDidMount() {
    this.onTokenRefreshListener = firebase.messaging().onTokenRefresh((fcmToken) => {
        // Process your token as required
    });
}
```

Please help to update the website to prevent misleading. Thank you.

**Comment by chrisbianca** [comment]
Please feel free to submit a PR to correct the documentation.

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase-docs/commit/a9511a3bd3ebcc4b8977e2de66e86bf1cc80978a
