### ISSUE TITLE
RemoteMessage object

### ISSUE THREAD

**Issue by t1amat9409** [invertase/react-native-firebase-docs#78]
Hi, what are the get methods for the RemoteMessage object, I can't seem to have notifications working when the app was completely closed/shutdown by user

Thanks

**Comment by t1amat9409** [comment]
I just wanna be able to display notifications on the tray, any help?

**Comment by Ehesp** [comment]
Please check out the notifications API here: https://rnfirebase.io/docs/v4.2.x/notifications/introduction

For any further help, it would be better to ask the questions on the main library providing all of the details required in the issue template: https://github.com/invertase/react-native-firebase

Thanks
